jobs:
- name: u16cppall
 type: runSh
       runtime:
         options:
           imageName: "drydock/u16cppall"
           imageTag: master
       script:
          - gcc --version
          - autoconf --version
          - automake --version
          - ccache --version
